name: Lint

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: false
        type: string
      PNPM_VERSION:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      NODE_VERSION:
        description: Node version used to run lint
        required: true
        type: string
        default: 20.17.0
      PNPM_VERSION:
        description: Pnpm version used to run lint
        required: true
        type: string
        default: 9.11.0

jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-latest
    steps:
    - name: Checks-out repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "${{ inputs.NODE_VERSION }}"
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      id: pnpm-install
      with:
        version: "${{ inputs.PNPM_VERSION }}"
        run_install: false

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Check lint error
      run: |
        pnpm run lint
